// MacScanner
// Copyright © 2026 Faiz Azhar Ristya Nugraha. All rights reserved.

import Foundation
import SwiftUI

/// Scanner for Designer & Creative application caches and Web Browser extensions & bloat.
enum DesignerBrowserScanner {

    // MARK: - Designer Caches

    static func candidateDesignCaches() -> [DesignAppCacheInfo] {
        let home = FileManager.default.homeDirectoryForCurrentUser
        let lib = home.appendingPathComponent("Library")
        let appSupport = lib.appendingPathComponent("Application Support")
        let caches = lib.appendingPathComponent("Caches")

        return [
            DesignAppCacheInfo(
                appName: "Figma App & Texture Cache",
                icon: "paintbrush.fill",
                category: "UI/UX Design",
                path: caches.appendingPathComponent("com.figma.Desktop"),
                explanation: "Figma webview engine caches, GPU texture caches, and font render temporary bitmaps. 100% safe to clear without affecting your logins, drafts, or Figma plugins.",
                safeToClean: true
            ),
            DesignAppCacheInfo(
                appName: "Adobe Media Cache (Common)",
                icon: "photo.stack.fill",
                category: "Video & Motion",
                path: appSupport.appendingPathComponent("Adobe/Common"),
                explanation: "Shared audio peak files and media cache generated by Premiere Pro and After Effects.",
                safeToClean: true
            ),
            DesignAppCacheInfo(
                appName: "Adobe Photoshop AutoRecover & Scratch",
                icon: "photo.fill",
                category: "Graphic Design",
                path: appSupport.appendingPathComponent("Adobe/Adobe Photoshop 2024/AutoRecover"),
                explanation: "Photoshop temporary autosaves and session recovery states.",
                safeToClean: true
            ),
            DesignAppCacheInfo(
                appName: "Adobe After Effects Disk Cache",
                icon: "sparkles.tv.fill",
                category: "Motion Graphics",
                path: caches.appendingPathComponent("Adobe/After Effects"),
                explanation: "Render preview frames and comp RAM cache. Can become massive (10-50 GB+). Safe to clear.",
                safeToClean: true
            ),
            DesignAppCacheInfo(
                appName: "Adobe Premiere Pro Caches",
                icon: "film.stack.fill",
                category: "Video Editing",
                path: caches.appendingPathComponent("Adobe/Premiere Pro"),
                explanation: "Premiere preview renders, waveform index files, and scratch cache.",
                safeToClean: true
            ),
            DesignAppCacheInfo(
                appName: "Adobe Creative Cloud Cache",
                icon: "cloud.fill",
                category: "Cloud Sync",
                path: caches.appendingPathComponent("Adobe/CoreSync"),
                explanation: "Creative Cloud libraries and shared asset sync cache.",
                safeToClean: true
            ),
            DesignAppCacheInfo(
                appName: "Sketch App Cache",
                icon: "diamond.fill",
                category: "UI/UX Design",
                path: caches.appendingPathComponent("com.bohemiancoding.sketch3"),
                explanation: "Sketch local document caches, canvas renders, and cloud symbol previews.",
                safeToClean: true
            ),
            DesignAppCacheInfo(
                appName: "Blender 3D Cache",
                icon: "cube.transparent.fill",
                category: "3D & VFX",
                path: caches.appendingPathComponent("Blender"),
                explanation: "Shader compilation cache, physics simulations, and render previews.",
                safeToClean: true
            ),
            DesignAppCacheInfo(
                appName: "DaVinci Resolve CacheClip",
                icon: "video.badge.waveform.fill",
                category: "Color Grading & Edit",
                path: appSupport.appendingPathComponent("Blackmagic Design/DaVinci Resolve/CacheClip"),
                explanation: "Optimized media, proxy renders, and timeline cache clips.",
                safeToClean: true
            ),
            DesignAppCacheInfo(
                appName: "CapCut Desktop Cache",
                icon: "scissors",
                category: "Video Editing",
                path: appSupport.appendingPathComponent("CapCut/User Data/Cache"),
                explanation: "Effects, sticker downloads, and video preview cache files.",
                safeToClean: true
            ),
            DesignAppCacheInfo(
                appName: "Canva Desktop Cache",
                icon: "wand.and.stars",
                category: "Graphic Design",
                path: caches.appendingPathComponent("com.canva.CanvaDesktop"),
                explanation: "Canva desktop template assets and rendered raster previews.",
                safeToClean: true
            )
        ]
    }

    static func scanDesignCaches(completion: @escaping ([DesignAppCacheInfo]) -> Void) {
        DispatchQueue.global(qos: .userInitiated).async {
            let fm = FileManager.default
            let list = candidateDesignCaches()
            var results: [DesignAppCacheInfo] = []

            for var item in list {
                var isDir: ObjCBool = false
                if fm.fileExists(atPath: item.path.path, isDirectory: &isDir) {
                    item.exists = true
                    item.sizeBytes = DiskScanner.size(of: item.path)
                    if item.sizeBytes > 1024 * 1024 { // at least 1MB to be notable
                        results.append(item)
                    }
                }
            }

            results.sort { $0.sizeBytes > $1.sizeBytes }
            DispatchQueue.main.async { completion(results) }
        }
    }

    // MARK: - Browser & Extensions Scanning

    static func scanBrowsers(completion: @escaping ([BrowserInfo]) -> Void) {
        DispatchQueue.global(qos: .userInitiated).async {
            let home = FileManager.default.homeDirectoryForCurrentUser
            let lib = home.appendingPathComponent("Library")
            let appSupport = lib.appendingPathComponent("Application Support")
            let caches = lib.appendingPathComponent("Caches")
            let fm = FileManager.default

            let configs: [(name: String, icon: String, tint: Color, appSupportSubpath: String, extensionsSubpath: String, cacheSubpath: String)] = [
                ("Google Chrome", "globe.americas.fill", .blue, "Google/Chrome", "Google/Chrome/Default/Extensions", "Google/Chrome"),
                ("Arc Browser", "circle.dashed.rectangle", .pink, "Arc/User Data", "Arc/User Data/Default/Extensions", "company.thebrowser.Browser"),
                ("Brave Browser", "shield.fill", .orange, "BraveSoftware/Brave-Browser", "BraveSoftware/Brave-Browser/Default/Extensions", "BraveSoftware/Brave-Browser"),
                ("Microsoft Edge", "e.circle.fill", .cyan, "Microsoft Edge", "Microsoft Edge/Default/Extensions", "Microsoft Edge"),
                ("Mozilla Firefox", "flame.circle.fill", .red, "Firefox", "Firefox/Profiles", "Firefox"),
                ("Opera", "o.circle.fill", .red, "com.operasoftware.Opera", "com.operasoftware.Opera/Extensions", "com.operasoftware.Opera"),
                ("Opera GX", "gamecontroller.fill", .red, "com.operasoftware.OperaGX", "com.operasoftware.OperaGX/Extensions", "com.operasoftware.OperaGX"),
                ("Vivaldi", "v.circle.fill", .red, "Vivaldi", "Vivaldi/Default/Extensions", "Vivaldi"),
                ("Orion Browser", "sparkles.rectangle.stack.fill", .purple, "Kagi/Orion", "", "com.kagi.kagimacOS"),
                ("Apple Safari", "safari.fill", .blue, "com.apple.Safari", "", "com.apple.Safari")
            ]

            var browserResults: [BrowserInfo] = []

            for cfg in configs {
                let supportDir = appSupport.appendingPathComponent(cfg.appSupportSubpath)
                let extDir = cfg.extensionsSubpath.isEmpty ? nil : appSupport.appendingPathComponent(cfg.extensionsSubpath)
                let cacheDir = caches.appendingPathComponent(cfg.cacheSubpath)

                let isInstalled = fm.fileExists(atPath: supportDir.path) || fm.fileExists(atPath: cacheDir.path)
                guard isInstalled else { continue }

                var cacheSize: Int64 = 0
                if fm.fileExists(atPath: cacheDir.path) {
                    cacheSize = DiskScanner.size(of: cacheDir)
                }

                var extensions: [BrowserExtensionInfo] = []
                if cfg.name == "Mozilla Firefox" {
                    extensions = parseFirefoxExtensions(in: supportDir)
                } else if let extDir = extDir, fm.fileExists(atPath: extDir.path) {
                    extensions = parseChromiumExtensions(at: extDir, browserName: cfg.name)
                }

                browserResults.append(
                    BrowserInfo(
                        name: cfg.name,
                        icon: cfg.icon,
                        tintColor: cfg.tint,
                        isInstalled: true,
                        cacheBytes: cacheSize,
                        extensions: extensions,
                        cacheURL: cacheDir,
                        extensionsURL: extDir
                    )
                )
            }

            DispatchQueue.main.async { completion(browserResults) }
        }
    }

    /// Parses Firefox profile extensions.json file.
    private static func parseFirefoxExtensions(in firefoxSupportDir: URL) -> [BrowserExtensionInfo] {
        let fm = FileManager.default
        let profilesDir = firefoxSupportDir.appendingPathComponent("Profiles")
        guard let profiles = try? fm.contentsOfDirectory(at: profilesDir, includingPropertiesForKeys: [.isDirectoryKey], options: [.skipsHiddenFiles]) else {
            return []
        }

        var results: [BrowserExtensionInfo] = []
        for profile in profiles {
            let extensionsJSON = profile.appendingPathComponent("extensions.json")
            guard let data = try? Data(contentsOf: extensionsJSON),
                  let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
                  let addons = json["addons"] as? [[String: Any]] else { continue }

            for addon in addons {
                guard let id = addon["id"] as? String,
                      let active = addon["active"] as? Bool, active,
                      let defaultLocale = addon["defaultLocale"] as? [String: Any],
                      let name = defaultLocale["name"] as? String else { continue }

                let version = addon["version"] as? String ?? "1.0"
                let desc = defaultLocale["description"] as? String ?? ""
                let isHeavy = isPotentialHeavyExtension(name: name, desc: desc)

                results.append(
                    BrowserExtensionInfo(
                        extensionID: id,
                        name: name,
                        version: version,
                        description: desc,
                        browserName: "Mozilla Firefox",
                        isHeavyCandidate: isHeavy
                    )
                )
            }
        }
        return results
    }

    /// Parses Chromium extension directories and reads manifest.json metadata for readable names.
    private static func parseChromiumExtensions(at url: URL, browserName: String) -> [BrowserExtensionInfo] {
        let fm = FileManager.default
        guard let extFolders = try? fm.contentsOfDirectory(at: url, includingPropertiesForKeys: [.isDirectoryKey], options: [.skipsHiddenFiles]) else {
            return []
        }

        var results: [BrowserExtensionInfo] = []

        for folder in extFolders {
            let extensionID = folder.lastPathComponent
            // Extension folder usually contains version folders (e.g. "1.4.2_0")
            guard let versionFolders = try? fm.contentsOfDirectory(at: folder, includingPropertiesForKeys: [.isDirectoryKey], options: [.skipsHiddenFiles]),
                  let latestVersion = versionFolders.first else {
                continue
            }

            let manifestURL = latestVersion.appendingPathComponent("manifest.json")
            guard let data = try? Data(contentsOf: manifestURL),
                  let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                continue
            }

            var name = json["name"] as? String ?? extensionID
            let version = json["version"] as? String ?? "1.0"
            var desc = json["description"] as? String ?? "Browser extension"

            // Localized Chrome message name lookup (e.g. "__MSG_appName__")
            if name.hasPrefix("__MSG_") {
                name = resolveLocalizedName(in: latestVersion, rawKey: name) ?? extensionID
            }
            if desc.hasPrefix("__MSG_") {
                desc = resolveLocalizedName(in: latestVersion, rawKey: desc) ?? desc
            }

            let isHeavy = isPotentialHeavyExtension(name: name, desc: desc)

            results.append(
                BrowserExtensionInfo(
                    extensionID: extensionID,
                    name: name,
                    version: version,
                    description: desc,
                    browserName: browserName,
                    isHeavyCandidate: isHeavy
                )
            )
        }

        return results.sorted { $0.name.lowercased() < $1.name.lowercased() }
    }

    private static func resolveLocalizedName(in versionFolder: URL, rawKey: String) -> String? {
        let key = rawKey
            .replacingOccurrences(of: "__MSG_", with: "")
            .replacingOccurrences(of: "__", with: "")

        let fm = FileManager.default
        let locales = ["en", "en_US", "en_GB", "id", "default"]
        for loc in locales {
            let msgFile = versionFolder.appendingPathComponent("_locales/\(loc)/messages.json")
            if fm.fileExists(atPath: msgFile.path),
               let data = try? Data(contentsOf: msgFile),
               let json = try? JSONSerialization.jsonObject(with: data) as? [String: [String: Any]],
               let item = json[key] ?? json[key.lowercased()],
               let message = item["message"] as? String {
                return message
            }
        }
        return nil
    }

    private static func isPotentialHeavyExtension(name: String, desc: String) -> Bool {
        let text = (name + " " + desc).lowercased()
        let heavyKeywords = [
            "record", "screen", "capture", "video", "download", "ai", "copilot",
            "chatgpt", "inspector", "debug", "adblock", "ublock", "grammarly",
            "vpn", "proxy", "translate", "scraper", "fitt"
        ]
        return heavyKeywords.contains { text.contains($0) }
    }

    // MARK: - Plain Language Diagnostics

    static func generatePlainLanguageInsights(
        designCaches: [DesignAppCacheInfo],
        browsers: [BrowserInfo],
        heaviestApps: [ProcessStats]
    ) -> [DesignerDiagnosticInsight] {
        var insights: [DesignerDiagnosticInsight] = []

        // 1. Creative Apps Memory & Cache Insights
        let totalDesignCache = designCaches.reduce(0) { $0 + $1.sizeBytes }
        if totalDesignCache > 5 * 1024 * 1024 * 1024 { // > 5 GB
            insights.append(
                DesignerDiagnosticInsight(
                    title: "Oversized Design & Media Caches",
                    summary: "\(ByteFormat.string(totalDesignCache)) of creative app cache is occupying disk space.",
                    explanation: "Apps like Adobe Premiere, After Effects, and Figma cache render preview frames and canvas data. Cleaning this cache is safe and immediately reclaims storage.",
                    icon: "paintbrush.pointed.fill",
                    color: .purple,
                    actionTitle: "Clean Design Caches",
                    targetURL: designCaches.first?.path
                )
            )
        }

        // 2. Heavy Browsers & Extensions
        for browser in browsers {
            if browser.extensionsCount >= 6 {
                insights.append(
                    DesignerDiagnosticInsight(
                        title: "\(browser.name) Has \(browser.extensionsCount) Active Extensions",
                        summary: "Numerous browser extensions inject scripts into every open tab, consuming memory.",
                        explanation: "Each browser extension adds background processing. Disabling unused extensions improves browser speed and reduces memory usage.",
                        icon: browser.icon,
                        color: browser.tintColor,
                        actionTitle: "Manage Extensions in \(browser.name)",
                        targetURL: browser.extensionsURL,
                        browserName: browser.name
                    )
                )
            }

            if browser.cacheBytes > 3 * 1024 * 1024 * 1024 { // > 3 GB
                insights.append(
                    DesignerDiagnosticInsight(
                        title: "\(browser.name) Web Cache Reached \(ByteFormat.string(browser.cacheBytes))",
                        summary: "Cached media, high-resolution images, and scripts have accumulated.",
                        explanation: "Clearing web cache frees up storage without deleting your passwords, logins, or bookmarks.",
                        icon: "globe",
                        color: browser.tintColor,
                        actionTitle: "Clear Web Cache",
                        targetURL: browser.cacheURL
                    )
                )
            }
        }

        // 3. Figma / Adobe Heavy Process Diagnostic
        let creativeAppNames = ["figma", "photoshop", "illustrator", "premiere", "after effects", "blender", "sketch", "resolve"]
        let runningCreative = heaviestApps.filter { proc in
            creativeAppNames.contains { proc.name.lowercased().contains($0) }
        }

        if let heaviest = runningCreative.max(by: { $0.memoryBytes < $1.memoryBytes }), heaviest.memoryBytes > 2 * 1024 * 1024 * 1024 {
            insights.append(
                DesignerDiagnosticInsight(
                    title: "\(heaviest.name) High Memory Usage (\(ByteFormat.string(heaviest.memoryBytes)))",
                    summary: "Open vector canvases or media projects are utilizing substantial RAM.",
                    explanation: "If zooming or panning feels sluggish, consider closing inactive project tabs or restarting the app to release memory.",
                    icon: "memorychip.fill",
                    color: .orange,
                    actionTitle: nil,
                    targetURL: nil
                )
            )
        }

        if insights.isEmpty {
            insights.append(
                DesignerDiagnosticInsight(
                    title: "Design & Browser Workspaces Optimal",
                    summary: "No excessive cache accumulation or heavy background extensions detected.",
                    explanation: "Your creative design apps and web browsers are running efficiently.",
                    icon: "checkmark.seal.fill",
                    color: .green,
                    actionTitle: nil,
                    targetURL: nil
                )
            )
        }

        return insights
    }

    /// Opens the official in-browser Extension Management page (chrome://extensions/, arc://extensions/, etc.)
    /// directly in the browser so the user can easily toggle off or remove extensions with 1 click.
    @MainActor
    static func openBrowserExtensionPage(browserName: String) {
        let lower = browserName.lowercased()
        if lower.contains("chrome") {
            _ = Shell.run("/usr/bin/open", ["-a", "Google Chrome", "chrome://extensions/"])
            ToastManager.shared.show("Opening extensions page in Google Chrome", icon: "puzzlepiece.extension.fill", tint: .blue)
        } else if lower.contains("arc") {
            _ = Shell.run("/usr/bin/open", ["-a", "Arc", "arc://extensions/"])
            ToastManager.shared.show("Opening extensions page in Arc", icon: "puzzlepiece.extension.fill", tint: .purple)
        } else if lower.contains("brave") {
            _ = Shell.run("/usr/bin/open", ["-a", "Brave Browser", "brave://extensions/"])
            ToastManager.shared.show("Opening extensions page in Brave", icon: "puzzlepiece.extension.fill", tint: .orange)
        } else if lower.contains("edge") {
            _ = Shell.run("/usr/bin/open", ["-a", "Microsoft Edge", "edge://extensions/"])
            ToastManager.shared.show("Opening extensions page in Microsoft Edge", icon: "puzzlepiece.extension.fill", tint: .cyan)
        } else if lower.contains("firefox") {
            _ = Shell.run("/usr/bin/open", ["-a", "Firefox", "about:addons"])
            ToastManager.shared.show("Opening add-ons page in Firefox", icon: "puzzlepiece.extension.fill", tint: .red)
        } else {
            _ = Shell.run("/usr/bin/open", ["https://support.apple.com/guide/safari/safari-extensions-sfri32508/mac"])
        }
    }
}
